version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/api_server"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/emotion_dashboard"
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
