FROM python:3.10-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y --no-install-recommends build-essential default-libmysqlclient-dev pkg-config libgl1 libglib2.0-0 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY api_server/requirements.txt /app/api_server/requirements.txt
RUN pip install --no-cache-dir -r /app/api_server/requirements.txt
COPY api_server /app/api_server
CMD ["uvicorn", "api_server.face_api:app", "--host", "0.0.0.0", "--port", "8001", "--proxy-headers"]
