# Generated by Django 5.2.14 on 2026-07-14 10:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='api_key_rotated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='code',
            field=models.SlugField(help_text='Unique bank code, for example FIDELITY_GH or BANK_A', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.SlugField(help_text='Branch code, for example RIDGE_TOWERS', max_length=30),
        ),
        migrations.CreateModel(
            name='BankSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Africa/Accra', max_length=64)),
                ('image_retention_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('record_retention_days', models.PositiveIntegerField(default=365, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('delete_images_after_retention', models.BooleanField(default=True)),
                ('offline_after_minutes', models.PositiveIntegerField(default=15, help_text='A computer is marked offline when no capture is received within this period.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='monitor.bank')),
            ],
            options={
                'verbose_name_plural': 'Bank settings',
                'db_table': 'tenant_bank_settings',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_date_range', models.CharField(choices=[('day', 'Today'), ('week', 'Last 7 days'), ('14days', 'Last 14 days'), ('month', 'Last 30 days')], default='14days', max_length=10)),
                ('default_hourly_range', models.CharField(choices=[('today', 'Today'), ('yesterday', 'Yesterday')], default='today', max_length=12)),
                ('auto_refresh_seconds', models.PositiveIntegerField(choices=[(0, 'Disabled'), (30, 'Every 30 seconds'), (60, 'Every minute'), (120, 'Every 2 minutes'), (300, 'Every 5 minutes')], default=0)),
                ('compact_mode', models.BooleanField(default=False)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('email_weekly_summary', models.BooleanField(default=False)),
                ('notify_negative', models.BooleanField(default=False)),
                ('negative_threshold', models.PositiveSmallIntegerField(default=35, help_text='Alert when negative emotions meet or exceed this percentage.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('minimum_detections', models.PositiveIntegerField(default=20, help_text='Minimum number of detections before an alert may be triggered.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='monitor.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'monitor_user_preference',
            },
        ),
    ]
