# Generated by Django 4.2.21 on 2025-05-21 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_uniquefaceid_table_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='monitor.branch'),
        ),
    ]
