# Generated by Django 4.2.21 on 2025-05-23 23:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_customuser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='monitor.branch'),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
