# Generated by Django 4.2.21 on 2025-05-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_visitlog_branch_alter_visitlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='face_records',
            field=models.ManyToManyField(blank=True, related_name='visitors', to='monitor.uniquefaceid'),
        ),
    ]
