# Generated by Django 4.2.21 on 2025-05-31 03:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_visitor_face_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='face_records',
        ),
        migrations.AddField(
            model_name='visitor',
            name='face_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
