# Generated by Django 4.2.21 on 2025-05-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_remove_visitor_face_records_visitor_face_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
