# Generated by Django 4.2.21 on 2025-06-04 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alter_visitor_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='monitor.branch'),
        ),
    ]
